Add files via upload
deniko1985/friendly_talk_bot pull request #1
Opened 2022-06-28 11:11 UTC by deniko1985

2022-06-28 11:30 UTC, arseniy-kozlov requested changes

2022-06-28 11:30 UTC, arseniy-kozlov commented on MessageHandler.py
> +        i = ma.parse(sentence)[0].normal_form
Переменные i, j принято использовать в качестве счетчика цикла, или индекса массива. Здесь, как я понимаю друг смысл, лучше переименовать.

2022-06-28 11:30 UTC, arseniy-kozlov commented on main.py
> +bot = telebot.TeleBot("Token")
Здесь необходимо использовать переменную окружения https://developer.vonage.com/blog/21/10/01/python-environment-variables-a-primer

ВАЖНО! Не забыть добавить .env в gitignore, чтобы он не пушился в публичный репозиторий

2022-06-28 11:30 UTC, arseniy-kozlov commented on MessageHandler.py
> +    def handle(sentence):
Методы не помечены, как статические

2022-06-28 11:30 UTC, arseniy-kozlov commented on MessageHandler.py
> +    def two_method(i):
Не очень понял смысл этой функции

2022-06-28 12:34 UTC, deniko1985 commented on MessageHandler.py
> +    def two_method(i):
Это функция для теста, чтобы увидеть как ведут себя данные, например: ('здрасте'), ('Здравствуй!', 100)

2022-06-28 12:35 UTC, deniko1985 commented on MessageHandler.py
> +        i = ma.parse(sentence)[0].normal_form
Ок

2022-06-28 12:39 UTC, deniko1985 commented on MessageHandler.py
> +    def handle(sentence):
Ok

2022-06-28 13:04 UTC, arseniy-kozlov commented on MessageHandler.py
> +    def two_method(i):
Посмотрел - удали) Не стоит оставлять тестовые функции в итоговом коде, это очень сильно загромождает код и усложняет его понимание.

2022-06-28 13:10 UTC, arseniy-kozlov requested changes
Не исправлены все замечания

2022-06-30 04:33 UTC, deniko1985 commented on main.py
> +bot = telebot.TeleBot("Token")
Исправил

2022-06-30 04:57 UTC, arseniy-kozlov approved these changes

2022-06-30 04:57 UTC, arseniy-kozlov commented on MessageHandler.py
> +    greeting_responses = np.array(text.split('\n'))
@deniko1985  Nit: После того, как прочитал файл, стоит его закрыть

2022-06-30 05:10 UTC, deniko1985 commented on MessageHandler.py
> +    greeting_responses = np.array(text.split('\n'))
Изменил на конструкцию with

2022-06-30 05:25 UTC, merged